---
title: "`r paste0(params$file.output.list$run_id,'_diagnostic_spatialautocorr')`"
author: ""
date: "`r paste0('Generated: ',format(Sys.time(), '%m-%d-%Y'))`"
output: html_document
params:
  path_masterFormat: path_masterFormat
  file.output.list: file.output.list
  mapping.input.list: mapping.input.list
  classvar: classvar
  sitedata: sitedata
  numsites: numsites 
  estimate.list: estimate.list
  estimate.input.list: estimate.input.list
  subdata: subdata
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE)
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, results = "hide"}
#unpack params
path_masterFormat<-params$path_masterFormat
file.output.list<-params$file.output.list
mapping.input.list<-params$mapping.input.list
classvar<-params$classvar
sitedata<-params$sitedata
numsites<-params$numsites 
estimate.list<-params$estimate.list
estimate.input.list<-params$estimate.input.list
subdata<-params$subdata


unPackList(lists = list(Mdiagnostics.list = estimate.list$Mdiagnostics.list,
                        estimate.input.list = estimate.input.list,
                        data.index.list = DataMatrix.list$data.index.list,
                        file.output.list = file.output.list,
                        mapping.input.list = mapping.input.list),
           parentObj = list(NA,
                            NA,
                            NA,
                            NA,
                            NA))

if (!dir.exists(paste0(path_results,.Platform$file.sep,"estimate",.Platform$file.sep,"diagnostic_spatialautocor_dynamic",.Platform$file.sep))){
                dir.create(paste0(path_results,.Platform$file.sep,"estimate",.Platform$file.sep,"diagnostic_spatialautocor_dynamic",.Platform$file.sep))
  
}

data.index.list = DataMatrix.list$data.index.list
#plotly setup  
hline <- function(y = 0, color = "red", dash = '') {
  list(
    type = "line", 
    x0 = 0, 
    x1 = 1, 
    xref = "paper",
    y0 = y, 
    y1 = y, 
    line = list(color = color, dash = dash)
  )
}

pnch<-as.character(pchPlotlyCross[pchPlotlyCross$pch==diagnosticPlotPointStyle,]$plotly)
markerSize<-diagnosticPlotPointSize*10
markerCols<-colorNumeric(c("black","white"), 1:2)
markerList = paste0("list(symbol = pnch,
                       size = ",markerSize,",")
if (regexpr("open",pnch)>0){
  markerList<-paste0(markerList,"color = markerCols(1))")
}else{
  markerList<-paste0(markerList,"line = list(color = markerCols(1), width = 0.8),color = markerCols(1))")
}

data <- DataMatrix.list$data
# nreach <- length(data[,1])
# nstas <- sum(ifelse(data[,jdepvar] > 0,1,0))  # jdepvar site load index

# contiguous class variables by sites
class <- array(0,dim=c(nrow=nrow(sitedata),ncol=length(classvar))) 
for (k in 1:length(classvar)) { 
  for (i in 1:nrow(sitedata)) {
    class[i,k] <- as.numeric(eval(parse(text=paste0("sitedata$",classvar[k],"[",i,"]"))))
  } 
}

set.ZeroPolicyOption(TRUE) # setting required for hydrological distance tests


#add text explanation

strExplanation<-paste("
  1. CDF of Station Hydrological Distances (units of 'length' variable)\n
  2. CDF of Station Euclidean Distances (kilometers)\n
  3. Four panel plot with Moran's I results by river basin:\n
      + P-value (Euclidean weights)\n
      + Standard deviate (Euclidean weights)\n
      + P-value (Hydrological weights)\n
      + Standard deviate (Hydrological weights)\n
  4. Two panel plot with Moran's I results by Class variable and full domain:\n
      + P-value (Euclidean weights)\n
      + Standard deviate (Euclidean weights)
          ")

```  

```{r  echo=FALSE, results='asis', eval=TRUE}

cat("## Document Contents ",strExplanation,sep="\n")
```

```{r pagebreak, results='asis', echo=FALSE}
cat("<P style='page-break-before: always'>") 
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"}
create_diagnosticPlotList()$p19$plotFunc(eval(parse(text =create_diagnosticPlotList()$p19$plotParams)))


```

```{r pagebreak0, results='asis', echo=FALSE}
cat("<P style='page-break-before: always'>") 
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"}
create_diagnosticPlotList()$p20$plotFunc(eval(parse(text =create_diagnosticPlotList()$p20$plotParams)))


```

```{r pagebreak1, results='asis', echo=FALSE}
cat("<P style='page-break-before: always'>") 

```



```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"}


create_diagnosticPlotList()$p21$plotFunc(eval(parse(text =create_diagnosticPlotList()$p21$plotParams)))

```



```{r pagebreak2, results='asis', echo=FALSE}
cat("<P style='page-break-before: always'>") 
```



```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.height="375px",out.width="750px"}
##########################################################################
# Plot Moran's I by Class variable (e.g., HUC-2)


dynamic<-FALSE
create_diagnosticPlotList()$p22$plotFunc(eval(parse(text =create_diagnosticPlotList()$p22$plotParams)))

```


