---
title: "`r params$rmdTitle`"
author: ""
date: "`r paste0('Output on ',format(Sys.time(), '%m-%d-%Y'))`"
output: html_document
params:
  rmdTitle: rmdTitle
  diagnostic_params: diagnostic_params
  plotIndex: plotIndex
  path_diagnosticPlotsNLLS_dynOutChild: path_diagnosticPlotsNLLS_dynOutChild
  
---



```{r outputMaps, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE,fig.width=8, fig.height=8}
#unpack params
path_diagnosticPlotsNLLS_dynOutChild<-params$path_diagnosticPlotsNLLS_dynOutChild
diagnostic_params<-params$diagnostic_params
plotIndex<-params$plotIndex

unPackList(lists = list(diagnostic_params = diagnostic_params),
           parentObj = list(NA))
unPackList(lists = list(mapping.input.list = mapping.input.list,
                        class.input.list = class.input.list),
           parentObj = list(NA,
                            NA))
plotList<-create_diagnosticPlotList()

if (!spatialAutoCorr){
hline <- function(y = 0, color = "red") {
  list(
    type = "line", 
    x0 = 0, 
    x1 = 1, 
    xref = "paper",
    y0 = y, 
    y1 = y, 
    line = list(color = color)
  )
}
}else{
  hline <- function(y = 0, color = "red", dash = '') {
  list(
    type = "line", 
    x0 = 0, 
    x1 = 1, 
    xref = "paper",
    y0 = y, 
    y1 = y, 
    line = list(color = color, dash = dash)
  )
}
}
pnch<-as.character(pchPlotlyCross[pchPlotlyCross$pch==diagnosticPlotPointStyle,]$plotly)
markerSize<-diagnosticPlotPointSize*10
markerCols<-colorNumeric(c("black","white"), 1:2)
markerList = paste0("list(symbol = pnch,
                       size = ",markerSize,",")
if (regexpr("open",pnch)>0){
  markerList<-paste0(markerList,"color = markerCols(1))")
}else{
  markerList<-paste0(markerList,"line = list(color = markerCols(1), width = 0.8),color = markerCols(1))")
}

# contiguous class variables by sites
class <- array(0,dim=c(nrow=nrow(sitedata),ncol=length(classvar))) 
for (k in 1:length(classvar)) { 
  for (i in 1:nrow(sitedata)) {
    class[i,k] <- as.numeric(eval(parse(text=paste0("sitedata$",classvar[k],"[",i,"]"))))
  } 
} 

#sensitivity plot list
    sPlot.list<-list()
    for (n in 1:length(names(plotList))){
      sTest2<-list()
      sTest<-plotList[[n]]
      if (sTest$sPlot==TRUE){
        eval(parse(text=paste0("sTest2$",names(plotList)[n],"<-sTest")))
        sPlot.list<-c(sPlot.list,sTest2)
      }
    }
   
    #spatialautocorr plot list
        sacPlot.list<-list()
    for (n in 1:length(names(plotList))){
      sTest2<-list()
      sTest<-plotList[[n]]
      if (sTest$sacPlot==TRUE){
        eval(parse(text=paste0("sTest2$",names(plotList)[n],"<-sTest")))
        sacPlot.list<-c(sacPlot.list,sTest2)
      }
    }  
    
if(!sensitivity & !spatialAutoCorr){
#run setup diagnostic
if (!validation){
  # create global variable from list names (Mdiagnostics.list)
  unPackList(lists = list(mapping.input.list = mapping.input.list,
                          Mdiagnostics.list = estimate.list$Mdiagnostics.list,
                          file.output.list = file.output.list,
                          class.input.list = class.input.list),
             parentObj = list(NA,
                              NA,
                              NA,
                              NA))
  Mdiagnostics.list <- estimate.list$Mdiagnostics.list
  
}else{
  unPackList(lists = list(mapping.input.list = mapping.input.list,
                          Mdiagnostics.list = estimate.list$vMdiagnostics.list,
                          file.output.list = file.output.list,
                          class.input.list = class.input.list),
             parentObj = list(NA,
                              NA,
                              NA,
                              NA))
  Mdiagnostics.list <- estimate.list$vMdiagnostics.list
  sitedata$staid<-sitedata$vstaid
}



# Create 'classvar2' for plotting landuse non-contiguous class
#   following code executes:  classvar2 <- c("forest_pct","agric_pct","urban_pct","shrubgrass_pct")
if(!is.na( class_landuse[1])){
  classvar2 <- character(length(class_landuse))
  for (i in 1:length(class_landuse)) {
    classvar2[i] <- paste0(class_landuse[i],"_pct")
  }
}

# Obtain CLASS region numbers
grp <- table(class[,1])   # get labels
xx <- as.data.frame(grp)  # convert table to dataframe...
grp <- as.numeric(levels(xx$Var1)[xx$Var1])  # convert factor levels to numeric values

plotList<-create_diagnosticPlotList()

  if (validation){
    vPlot.list<-list()
    for (n in 1:length(names(plotList))){
      vTest2<-list()
      vTest<-plotList[[n]]
      if (vTest$vPlot==TRUE){
        eval(parse(text=paste0("vTest2$",names(plotList)[n],"<-vTest")))
        vPlot.list<-c(vPlot.list,vTest2)
      }
    }
    plotList<-vPlot.list
  }

#remove sensitivity plots and spatial auto corr plots

plotList<-plotList[which(!names(plotList) %in% c(names(sPlot.list),names(sacPlot.list)))]
    
}else if (sensitivity){#sensitivity

#take only sensitivity plots
    plotList<-sPlot.list



  unPackList(lists = list(SelParmValues = SelParmValues,
                        JacobResults = estimate.list$JacobResults,
                        file.output.list = file.output.list,
                        mapping.input.list = mapping.input.list),
           parentObj = list(NA,
                            NA,
                            NA,
                            NA))
  

#depvar <- subdata$depvar
#xclass <- eval(parse(text=paste0("subdata$",classvar[1])))

# required SPARROW estimated coefficients (oEstimate, Parmnames)
Estimate <- oEstimate  # initial baseline estimates

# obtain baseline predictions all reaches
# predict <- predictSensitivity(Estimate,estimate.list,DataMatrix.list,SelParmValues,
#                               reach_decay_specification,reservoir_decay_specification,subdata)

# apredict <- predict
# apredict_sum <- matrix(1,nrow=length(depvar),ncol=length(Estimate))

ct <- length(Estimate)
xiqr <- matrix(0,nrow=4,ncol=sum(ct))
xmed <- numeric(sum(ct))
xparm <- character(sum(ct))
xvalue2 <- numeric(sum(ct))
# xsens <- matrix(0,nrow=sum(depvar > 0),ncol=length(Estimate))

# for (i in 1:length(Estimate)) {
#   if(betaconstant[i] == 0) {     # an estimated parameter
#     #  adjust parameter by 1%
#     AEstimate <- Estimate
#     AEstimate[i] <- Estimate[i] * 0.99
#     apredict <- predictSensitivity(AEstimate,estimate.list,DataMatrix.list,SelParmValues,
#                                    reach_decay_specification,reservoir_decay_specification,subdata)
#     apredict_sum[,i] <- abs((apredict-predict)/predict*100) / 1.0  # change relative to 1% change
#   }
# }
}else if (spatialAutoCorr){
  plotList<-sacPlot.list
  data.index.list = DataMatrix.list$data.index.list
  unPackList(lists = list(Mdiagnostics.list = estimate.list$Mdiagnostics.list,
                        estimate.input.list = estimate.input.list,
                        data.index.list = DataMatrix.list$data.index.list,
                        file.output.list = file.output.list,
                        mapping.input.list = mapping.input.list),
           parentObj = list(NA,
                            NA,
                            NA,
                            NA,
                            NA))
  set.ZeroPolicyOption(TRUE) 
}
```

```{r  echo=FALSE, results='asis', eval=TRUE}
cat(eval(parse(text=paste0("plotList$",plotIndex,"$header"))))
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"} 
p.list<-list()

if (diagnosticPlots_timestep=="season"){
  diagnosticPlots_timestep<-unique(sitedata$season)
     diagnosticPlots_timestep<-diagnosticPlots_timestep[match(c("winter","spring","summer","fall"),diagnosticPlots_timestep)]
}else if (diagnosticPlots_timestep=="year"){
  diagnosticPlots_timestep<-unique(sitedata$year)
}

if (!plotIndex %in% c("p4","p6","p7","p8","p11","p13","p14","p15","p16")){
  for (t in diagnosticPlots_timestep){
if (!sensitivity & !spatialAutoCorr){
    if (!validation){
     MdiagSub<-estimate.list$Mdiagnostics.list 
    }else{
     MdiagSub<-estimate.list$vMdiagnostics.list 
    }
    
    if (diagnosticPlots_timestep %in% unique(sitedata$year)){
      subStaid<-sitedata[sitedata$year==t ,]$staid
    }else{
      subStaid<-sitedata[sitedata$season==t,]$staid 
    }
    

    # MdiagSub<-MdiagSub[MdiagSub$xstaid %in% subStaid,]
    MdiagSub<-lapply(Mdiagnostics.list,function(x) x[which(MdiagSub$xstaid %in% subStaid)])

    unPackList(lists = list(MdiagSub = MdiagSub),
               parentObj = list(NA))
    
    sitedata_orig<-sitedata
    sitedata<-sitedata[sitedata$staid %in% subStaid,]
    
    sitedata.demtarea.class_orig<-sitedata.demtarea.class
    sitedata.demtarea.class<-sitedata.demtarea.class[which(sitedata$staid %in% subStaid)]
}else if (sensitivity){#sensitivity
         if (diagnosticPlots_timestep %in% unique(sitedata$year)){
      subWaterId<-subdata[subdata$year==t ,]$waterid
    }else{
      subWaterId<-subdata[subdata$season==t,]$waterid 
    }
      subdataTstep<-subdata[subdata$waterid %in% subWaterId,]
      DMLdatasub<-DataMatrix.list$data
      DMLdatasub<-DMLdatasub[which(DMLdatasub[,c(1)] %in% subWaterId),]
      subDataMatrix.list<-DataMatrix.list
      subDataMatrix.list$data<-DMLdatasub
      depvar <- subdataTstep$depvar
      xclass <- eval(parse(text=paste0("subdataTstep$",classvar[1])))
      
predict <- predictSensitivity(Estimate,estimate.list,DataMatrix.list = subDataMatrix.list,
                            SelParmValues,reach_decay_specification,reservoir_decay_specification,
                            subdata = subdataTstep)

apredict <- predict
apredict_sum <- matrix(1,nrow=length(depvar),ncol=length(Estimate))
xsens <- matrix(0,nrow=sum(depvar > 0),ncol=length(Estimate))

for (j in 1:length(Estimate)) {
  if(betaconstant[j] == 0) {     # an estimated parameter
    #  adjust parameter by 1%
    AEstimate <- Estimate
    AEstimate[j] <- Estimate[j] * 0.99
    apredict <- predictSensitivity(AEstimate,estimate.list,
                                   DataMatrix.list = subDataMatrix.list,SelParmValues,
                                   reach_decay_specification,reservoir_decay_specification,
                                   subdata = subdataTstep)
    apredict_sum[,j] <- abs((apredict-predict)/predict*100) / 1.0  # change relative to 1% change
  }
}
     
  
}else if (spatialAutoCorr){
  
           if (diagnosticPlots_timestep %in% unique(sitedata$year)){
      subWaterId<-subdata[subdata$year==t ,]$waterid
    }else{
      subWaterId<-subdata[subdata$season==t,]$waterid 
    }
  subdata_orig<-subdata
  subdata<-subdata[subdata$waterid %in% subWaterId,]
  
  # minnum <- minimum_reaches_separating_sites
  # sid <- ifelse(subdata$depvar > 0,subdata$staid,0)
  # subdata$staidseq <- assignIncremSiteIDs(minnum,sid,subdata$waterid,subdata$tnode,subdata$fnode) 
  
    Csites.list <- selectCalibrationSites(subdata,data_names,min.sites.list)
  
  waterid <- Csites.list$waterid
  depvar <- Csites.list$depvar
  staid <- Csites.list$staid
  staidseq <- Csites.list$staidseq
  xx <- data.frame(waterid,staid,staidseq,depvar)
  drops <- c("depvar","staid","staidseq")
  subdata <- subdata[ , !(names(subdata) %in% drops)]
  subdata <- merge(subdata,xx,by="waterid",all.y=FALSE,all.x=FALSE)
  subdata <- subdata[with(subdata,order(subdata$hydseq)), ]     # resort by the original HYDSEQ order
  
        DMLdatasub<-DataMatrix.list$data
      DMLdatasub<-DMLdatasub[which(DMLdatasub[,c(1)] %in% subWaterId),]
      subDataMatrix.list<-DataMatrix.list
      subDataMatrix.list$data<-DMLdatasub
      
      DataMatrix.list_orig<-DataMatrix.list
      DataMatrix.list<-subDataMatrix.list
      
  data <- DataMatrix.list$data

  sitedata_orig<-sitedata
  sitedata<-sitedata[sitedata$waterid %in% subWaterId,]
  sitedata<-sitedata[,names(sitedata)!="staid"]
  sitedata<-merge(sitedata,subdata[c("waterid","staid")],by="waterid")

 
  MdiagSub<-estimate.list$Mdiagnostics.list 
  MdiagSub<-lapply(Mdiagnostics.list,function(x) x[which(MdiagSub$xstaid %in% sitedata$staid)])
Mdiagnostics.list_orig<-Mdiagnostics.list
Mdiagnostics.list<-MdiagSub
dynamic<-TRUE
 
# contiguous class variables by sites
class <- array(0,dim=c(nrow=nrow(sitedata),ncol=length(classvar)))
for (k in 1:length(classvar)) {
  for (i in 1:nrow(sitedata)) {
    class[i,k] <- as.numeric(eval(parse(text=paste0("sitedata$",classvar[k],"[",i,"]"))))
  }
}

numsites <- length(sitedata$waterid)


}#end spatialAutoCorr
    plotParam.list<-eval(parse(text = paste0("plotList$",plotIndex,"$plotParams")))
    plotParam.list<-eval(parse(text = plotParam.list))
    
    if (plotIndex=="p12"){
      plotParam.list$ratio.obs.pred<-pratio.obs.pred
    }
    
    p<-eval(parse(text = paste0("plotList$",plotIndex,"$plotFunc(plotParam.list)"))) 
    
    eval(parse(text=paste0("p.list$p",which(t==diagnosticPlots_timestep),"<-p")))
    
    if (!sensitivity & !spatialAutoCorr){
    sitedata<-sitedata_orig
    sitedata.demtarea.class<-sitedata.demtarea.class_orig
    }
    
    if (spatialAutoCorr){
    subdata<-subdata_orig
    DataMatrix.list<-DataMatrix.list_orig
    sitedata<-sitedata_orig
    Mdiagnostics.list<-Mdiagnostics.list_orig
      }
    
  } 
}else{#plotIndex==p4
  if (plotIndex %in% c("p4","p11")){
    condList<-"!is.na(Cor.ExplanVars.list)"
  }else if (plotIndex %in% c("p6","p13")){
    condList<-"classvar!='sitedata.demtarea.class'"
  }else if (plotIndex %in% c("p7","p14")){
    condList<-"!is.na( class_landuse[1])"
  }else if (plotIndex %in% c("p8","p15","p16")){
    condList<-"TRUE"
  }
  
  
  if(eval(parse(text=condList))){ 
    
    if (plotIndex %in% c("p4","p11")){
      condLoop<-Cor.ExplanVars.list$names
    }else if (plotIndex %in% c("p6","p13")){
      condLoop<-classvar
    }else if (plotIndex %in% c("p7","p14")){
      condLoop<-classvar2
    }else if (plotIndex %in% c("p8","p15")){
      condLoop<-grp
    }else if (plotIndex=="p16"){
      condLoop<-Estimate
    }
    
    for (i in 1:(length(condLoop))){
      
      for (t in diagnosticPlots_timestep){
        if (!sensitivity){
        if (!validation){
         MdiagSub<-estimate.list$Mdiagnostics.list 
        }else{
          MdiagSub<-estimate.list$vMdiagnostics.list
        }
        
        if (diagnosticPlots_timestep %in% unique(sitedata$year)){
          subStaid<-sitedata[sitedata$year==t ,]$staid
        }else{
          subStaid<-sitedata[sitedata$season==t,]$staid  
        }
        
        MdiagSub<-lapply(Mdiagnostics.list,function(x) x[which(MdiagSub$xstaid %in% subStaid)])
        
        unPackList(lists = list(MdiagSub = MdiagSub),
                   parentObj = list(NA))
        
        if (plotIndex=="p4"){
          corrData<-ratio.obs.pred
        }else{
          corrData<-pratio.obs.pred 
        }
        if (plotIndex %in% c("p6","p7")){
          boxvar<-ratio.obs.pred 
        }else{
          boxvar<-pratio.obs.pred
        }
        
        
        sitedata_orig<-sitedata
        sitedata<-sitedata[sitedata$staid %in% subStaid,]
        
        sitedata.landuse_orig<-sitedata.landuse
        if (!validation){
         sitedata.landuse<-sitedata.landuse[which(estimate.list$Mdiagnostics.list$xstaid %in% subStaid),] 
        }else{
                  sitedata.landuse<-sitedata.landuse[which(estimate.list$vMdiagnostics.list$xstaid %in% subStaid),] 
 
        }
        
        
        if(!is.na(Cor.ExplanVars.list) & plotIndex %in% c("p4","p11")){ 
          Cor.ExplanVars.list_orig<-Cor.ExplanVars.list
          Cor.ExplanVars.list$cmatrixM_all<-Cor.ExplanVars.list$cmatrixM_all[which(estimate.list$Mdiagnostics.list$xstaid %in% subStaid),]
        }
        
        }else{#sensitivity
         if (diagnosticPlots_timestep %in% unique(sitedata$year)){
      subWaterId<-subdata[subdata$year==t ,]$waterid
    }else{
      subWaterId<-subdata[subdata$season==t,]$waterid 
    }
      subdataTstep<-subdata[subdata$waterid %in% subWaterId,]
      DMLdatasub<-DataMatrix.list$data
      DMLdatasub<-DMLdatasub[which(DMLdatasub[,c(1)] %in% subWaterId),]
      subDataMatrix.list<-DataMatrix.list
      subDataMatrix.list$data<-DMLdatasub
      depvar <- subdataTstep$depvar
      xclass <- eval(parse(text=paste0("subdataTstep$",classvar[1])))
      
predict <- predictSensitivity(Estimate,estimate.list,DataMatrix.list = subDataMatrix.list,
                            SelParmValues,reach_decay_specification,reservoir_decay_specification,
                            subdata = subdataTstep)

apredict <- predict
apredict_sum <- matrix(1,nrow=length(depvar),ncol=length(Estimate))
xsens <- matrix(0,nrow=sum(depvar > 0),ncol=length(Estimate))

for (j in 1:length(Estimate)) {
  if(betaconstant[j] == 0) {     # an estimated parameter
    #  adjust parameter by 1%
    AEstimate <- Estimate
    AEstimate[j] <- Estimate[j] * 0.99
    apredict <- predictSensitivity(AEstimate,estimate.list,
                                   DataMatrix.list = subDataMatrix.list,SelParmValues,
                                   reach_decay_specification,reservoir_decay_specification,
                                   subdata = subdataTstep)
    apredict_sum[,j] <- abs((apredict-predict)/predict*100) / 1.0  # change relative to 1% change
  }
}
      
    }#end sensitivity
        plotParam.list<-eval(parse(text = paste0("plotList$",plotIndex,"$plotParams")))
        plotParam.list<-eval(parse(text = plotParam.list))
        
        if (plotIndex=="p15"){
          plotParam.list$predict<-ppredict
          plotParam.list$yldobs<-pyldobs
          plotParam.list$yldpredict<-pyldpredict
          plotParam.list$Resids<-pResids
        }
        
        p<-eval(parse(text = paste0("plotList$",plotIndex,"$plotFunc(plotParam.list)"))) 
        
        eval(parse(text=paste0("p.list$p",i,which(t==diagnosticPlots_timestep),"<-p")))
        if (!sensitivity){
        sitedata<-sitedata_orig
        if(!is.na(Cor.ExplanVars.list)){ 
          Cor.ExplanVars.list<-Cor.ExplanVars.list_orig
        }
        sitedata.landuse<-sitedata.landuse_orig
        }
      }
    }
  }
}

if (!plotIndex %in% c("p4","p6","p7","p8","p11","p13","p14","p15","p16")){
  rmd <- sapply(
    1:(length(names(p.list))),
    function(i) {
      knitr::knit_expand(path_diagnosticPlotsNLLS_dynOutChild, i = i)
    }
  )
  rmd <- paste(rmd, collapse = "\n")
}else if (plotIndex %in% c("p4","p11")){#p4
  rmd <- sapply(
    as.numeric(gsub("p","",names(p.list))),
    function(i) {
      knitr::knit_expand(gsub("diagnosticPlotsNLLS_dynChild.Rmd","diagnosticPlotsNLLS_dynChildCorr.Rmd",
                              path_diagnosticPlotsNLLS_dynOutChild), i = i)
    }
  )
  rmd <- paste(rmd, collapse = "\n")
}else if (plotIndex %in% c("p6","p13")){
  rmd <- sapply(
    as.numeric(gsub("p","",names(p.list))),
    function(i) {
      knitr::knit_expand(gsub("diagnosticPlotsNLLS_dynChild.Rmd","diagnosticPlotsNLLS_dynChildClassvar.Rmd",
                              path_diagnosticPlotsNLLS_dynOutChild), i = i)
    }
  )
  rmd <- paste(rmd, collapse = "\n")   
  
}else if (plotIndex %in% c("p7","p14")){
  rmd <- sapply(
    as.numeric(gsub("p","",names(p.list))),
    function(i) {
      knitr::knit_expand(gsub("diagnosticPlotsNLLS_dynChild.Rmd","diagnosticPlotsNLLS_dynChildClassLand.Rmd",
                              path_diagnosticPlotsNLLS_dynOutChild), i = i)
    }
  )
  rmd <- paste(rmd, collapse = "\n")   
}else if (plotIndex %in% c("p8","p15")){
  rmd <- sapply(
    as.numeric(gsub("p","",names(p.list))),
    function(i) {
      knitr::knit_expand(gsub("diagnosticPlotsNLLS_dynChild.Rmd","diagnosticPlotsNLLS_dynChildContiguous.Rmd",
                              path_diagnosticPlotsNLLS_dynOutChild), i = i)
    }
  )
  rmd <- paste(rmd, collapse = "\n")   
}else if (plotIndex=="p16"){
   rmd <- sapply(
    as.numeric(gsub("p","",names(p.list))),
    function(i) {
      knitr::knit_expand(gsub("diagnosticPlotsNLLS_dynChild.Rmd","diagnosticSens_dynParamChild.Rmd",
                              path_diagnosticPlotsNLLS_dynOutChild), i = i)
    }
  )
  rmd <- paste(rmd, collapse = "\n")   
}
```

```{r renderOut, echo=FALSE, results='asis', warning=FALSE, message=FALSE}

rendered <- knitr::knit(text = rmd, quiet = TRUE)
cat("\n \n")
cat(rendered, sep = "\n")


```

