---
title: "`r paste0(params$file.output.list$run_id,'_diagnostic_plots')`"
author: ""
date: "`r paste0('Generated: ',format(Sys.time(), '%m-%d-%Y'))`"
output: html_document
params:
  validation: validation
  file.output.list: file.output.list
  path_diagnosticMapAttrChild: path_diagnosticMapAttrChild
  path_diagnosticCorrChild: path_diagnosticCorrChild
  path_diagnosticClassvarChild: path_diagnosticClassvarChild
  path_diagnosticClassLandChild: path_diagnosticClassLandChild
  path_diagnosticContiguousChild: path_diagnosticContiguousChild
  path_diagnosticDiagMapChild: path_diagnosticDiagMapChild
  path_outputMapsChild: path_outputMapsChild
  path_outputMaps: path_outputMaps
  class.input.list: class.input.list
  sitedata.demtarea.class: sitedata.demtarea.class
  sitedata: sitedata
  sitedata.landuse: sitedata.landuse
  estimate.list: estimate.list
  mapping.input.list: mapping.input.list
  Csites.weights.list: Csites.weights.list
  Cor.ExplanVars.list: Cor.ExplanVars.list
  data_names: data_names
  add_vars: add_vars
  batch_mode: batch_mode
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE)
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}
#unpack params
validation<-params$validation
file.output.list<-params$file.output.list
path_diagnosticMapAttrChild<-params$path_diagnosticMapAttrChild
path_diagnosticCorrChild<-params$path_diagnosticCorrChild
path_diagnosticClassvarChild<-params$path_diagnosticClassvarChild
path_diagnosticClassLandChild<-params$path_diagnosticClassLandChild
path_diagnosticContiguousChild<-params$path_diagnosticContiguousChild
path_diagnosticDiagMapChild<-params$path_diagnosticDiagMapChild
path_outputMapsChild<-params$path_outputMapsChild
path_outputMaps<-params$path_outputMaps
class.input.list<-params$class.input.list
sitedata.demtarea.class<-params$sitedata.demtarea.class
sitedata<-params$sitedata
sitedata.landuse<-params$sitedata.landuse
estimate.list<-params$estimate.list
mapping.input.list<-params$mapping.input.list
Csites.weights.list<-params$Csites.weights.list
Cor.ExplanVars.list<-params$Cor.ExplanVars.list
data_names<-params$data_names
add_vars<-params$add_vars
batch_mode<-params$batch_mode

if (!validation){
  # create global variable from list names (Mdiagnostics.list)
  unPackList(lists = list(mapping.input.list = mapping.input.list,
                          Mdiagnostics.list = estimate.list$Mdiagnostics.list,
                          file.output.list = file.output.list,
                          class.input.list = class.input.list),
             parentObj = list(NA,
                              NA,
                              NA,
                              NA))
  Mdiagnostics.list<-estimate.list$Mdiagnostics.list
}else{
  unPackList(lists = list(mapping.input.list = mapping.input.list,
                          vMdiagnostics.list = estimate.list$vMdiagnostics.list,
                          file.output.list = file.output.list,
                          class.input.list = class.input.list),
             parentObj = list(NA,
                              NA,
                              NA,
                              NA))
}

hline <- function(y = 0, color = "red") {
  list(
    type = "line", 
    x0 = 0, 
    x1 = 1, 
    xref = "paper",
    y0 = y, 
    y1 = y, 
    line = list(color = color)
  )
}
pnch<-as.character(pchPlotlyCross[pchPlotlyCross$pch==diagnosticPlotPointStyle,]$plotly)
markerSize<-diagnosticPlotPointSize*10
markerCols<-colorNumeric(c("black","white"), 1:2)
markerList = paste0("list(symbol = pnch,
                       size = ",markerSize,",")
if (regexpr("open",pnch)>0){
  markerList<-paste0(markerList,"color = markerCols(1))")
}else{
  markerList<-paste0(markerList,"line = list(color = markerCols(1), width = 0.8),color = markerCols(1))")
}

# contiguous class variables by sites
class <- array(0,dim=c(nrow=nrow(sitedata),ncol=length(classvar))) 
for (k in 1:length(classvar)) { 
  for (i in 1:nrow(sitedata)) {
    class[i,k] <- as.numeric(eval(parse(text=paste0("sitedata$",classvar[k],"[",i,"]"))))
  } 
} 

# Create 'classvar2' for plotting landuse non-contiguous class
#   following code executes:  classvar2 <- c("forest_pct","agric_pct","urban_pct","shrubgrass_pct")
if(!is.na( class_landuse[1])){
  classvar2 <- character(length(class_landuse))
  for (i in 1:length(class_landuse)) {
    classvar2[i] <- paste0(class_landuse[i],"_pct")
  }
}

#check if dynamic
dynamic<-checkDynamic(subdata) 



#start pdf output

################################    
#map site attributes
################################
existGeoLines<-checkBinaryMaps(LineShapeGeo,path_gis,batch_mode)
if (!validation){  
  if(!identical(NA,map_siteAttributes.list) & existGeoLines){
    strExplanation1<-TRUE
    strExplanation<-"#### Output is presented for the following sections:
1. Calibration Site Maps for User-Selected Attributes
2. Model Estimation Performance Diagnostics
3. Model Simulation Performance Diagnostics
4. Maps of Model Residuals and Observed to Predicted Ratios for the Calibration Sites"
  }else if (existGeoLines){
    strExplanation<-"### Output is presented for the following sections:
1. Model Estimation Performance Diagnostics
2. Model Simulation Performance Diagnostics
3. Maps of Model Residuals and Observed to Predicted Ratios for the Calibration Sites"
  }else{
    strExplanation<-"### Output is presented for the following sections:
1. Model Estimation Performance Diagnostics
2. Model Simulation Performance Diagnostics"
  }
}else{#validation text
  if (existGeoLines){
    strExplanation<-"### Output is presented for the following sections:
1. Model Simulation Performance Diagnostics
2. Maps of Model Residuals and Observed to Predicted Ratios for the Calibration Sites"
  }else{
    strExplanation<-"### Model Simulation Performance Diagnostics"
  }
}
```

```{r  echo=FALSE, results='asis', eval=TRUE}

cat("### Document Contents ",strExplanation,sep="\n")

```

```{r pagebreak1, results='asis', echo=FALSE}
if (!validation){ 
  cat("<P style='page-break-before: always'>") 
}
```

```{r  echo=FALSE, results='asis', eval=TRUE}
if (!validation){   
  if(existGeoLines) { 
    
    #map site attributes
    if (!identical(NA,map_siteAttributes.list)){
      if (identical(NA,map_years) & identical(NA,map_seasons)){#if static model
      cat("## Calibration Site Maps for User-Selected Attributes\n")
      }
    }
  }
}
```


```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}  

#    #map site attributes

if (!validation){ 
  if(existGeoLines) { 
    map_siteAttributes.list<-map_siteAttributes.list[which(map_siteAttributes.list %in% names(sitedata))]  
    #map site attributes
    if(length(map_siteAttributes.list)!=0){
    if (!identical(NA,map_siteAttributes.list)){
    
      if (!dynamic){
     # if (is.na(map_years) & is.na(map_seasons)){#if static model
      rmd <- sapply(
        1:(length(map_siteAttributes.list)),
        function(s) {
          knit_expand(path_diagnosticMapAttrChild, s = s)
        }
      )
      rmd <- paste(rmd, collapse = "\n")
      }else{#dynamic
      mapType<-"site"
          aggFuncs<-c("mean","median","min","max")
          
          if(!identical(NA,map_years)){
          if (identical(map_years,"all")){
            map_years<-unique(sitedata$year)
          }}
          if(!identical(map_seasons,NA)){
         if (identical(map_seasons,"all")){
            map_seasons<-unique(sitedata$season)
         }
          }
          
          if(!identical(NA,map_years)){
          if (length(map_years)!=0 & !map_years[1] %in% aggFuncs){
            map_years<-as.numeric(map_years)
          }else if (length(map_years)==0){
            map_years<-NA
          }}
          if(!identical(NA,map_seasons)){
          if (length(map_seasons)==0){
            map_seasons<-NA
          }}
          

          
for (attr in map_siteAttributes.list){
          mapColumn<-attr
          attrData<-eval(parse(text=paste0("sitedata$",mapColumn)))
          MAPID <- eval(parse(text=paste0("sitedata$","waterid_for_RSPARROW_mapping") )) 
          commonvar<-"tempID"
          input<-list(var=NA, sizeBatch=NA,size=NA)
          
          if (!all(is.na(attrData))){
          
          agg_map.list<-aggDynamicMapdata(map_years,map_seasons,
                                          enable_plotlyMaps,
                                          add_plotlyVars,
                                          aggFuncs,vvar = attrData,MAPID,commonvar,subdata = sitedata)
          unPackList(lists = list(agg_map.list = agg_map.list),
                     parentObj = list(NA)) 

          #prep aggdata for plots
          mapdata<-merge(uniqueSubdata,mapdata, 
               by=names(mapdata)[names(mapdata) %in% names(uniqueSubdata)])
          names(mapdata)[names(mapdata)=="vvar"]<-mapColumn
          if (length(map_years[map_years %in% aggFuncs])!=0 | length(map_seasons[map_seasons %in% aggFuncs])!=0){
           names(mapdata)[names(mapdata)==commonvar]<-"mapping_waterid"
           add_plotlyVars<-as.character(ifelse(add_plotlyVars=="waterid","mapping_waterid",add_plotlyVars))
          }else{
           names(mapdata)[names(mapdata)==commonvar]<-"waterid_for_RSPARROW_mapping" 
           add_plotlyVars<-as.character(ifelse(add_plotlyVars=="waterid","waterid_for_RSPARROW_mapping",add_plotlyVars))
          }
          
          plots<-setupDynamicMaps(mapdata,map_years,map_seasons,
                                  mapPageGroupBy,mapsPerPage, Rshiny=FALSE, 
                                  enable_plotlyMaps)

          mapLoopInput.list<-list(plots = plots,
                                  input = input,
                                  attr="", 
                                  path_gis = path_gis, 
                                  sitedata = mapdata, 
                                  LineShapeGeo = LineShapeGeo,
                                  data_names = data_names,
                                  Rshiny = FALSE,
                                  #regular
                                  mapColumn = mapColumn,
                                  dmapfinal = mapdata,
                                  GeoLines = GeoLines,
                                  mapping.input.list = mapping.input.list,
                                  # strTitle = strTitle,
                                  # unitAttr = unitAttr,
                                  batch_mode = batch_mode)
          
if (!dir.exists(paste0(path_results,.Platform$file.sep,"estimate",.Platform$file.sep,"diagnosticPlotsNLLS_dynamic",.Platform$file.sep))){
                dir.create(paste0(path_results,.Platform$file.sep,"estimate",.Platform$file.sep,"diagnosticPlotsNLLS_dynamic",.Platform$file.sep))
}
if (!dir.exists(paste0(path_results,.Platform$file.sep,"estimate",.Platform$file.sep,"diagnosticPlotsNLLS_dynamic",.Platform$file.sep,"mapSiteAttributes",.Platform$file.sep))){
                dir.create(paste0(path_results,.Platform$file.sep,"estimate",.Platform$file.sep,"diagnosticPlotsNLLS_dynamic",.Platform$file.sep,"mapSiteAttributes",.Platform$file.sep))
}
          
filename<- paste0(path_results,.Platform$file.sep,"estimate",.Platform$file.sep,"diagnosticPlotsNLLS_dynamic",.Platform$file.sep,"mapSiteAttributes",.Platform$file.sep,mapColumn,".html")
         # htmlFile<-gsub("pdf","html",filename)


         #path_predictMapsChild<-file_path_as_absolute(paste0(path_master,"predictMapsChild.Rmd"))
          rmdTitle<-mapColumn
          #path_outputMapsChild<-file_path_as_absolute(paste0(path_master,"outputMapsChild.Rmd"))

            rmarkdown::render(path_outputMaps,
            params = list(
              rmdTitle = rmdTitle,
              mapType = "site",
              mapLoopInput.list = mapLoopInput.list,
              path_outputMapsChild = path_outputMapsChild
            ),
            envir = new.env(),
            output_file = filename, quiet = TRUE
          )
          }else{#all NA mapdata
  message(paste0(mapColumn," CONTAINS ONLY NAs mapSiteAttributes NOT RUN"))
}

}#for each attr
    }#if dynamic
    }#if mapsite attr
    }
  }#if existGeolines
}else{#validation

if (!dir.exists(paste0(path_results,.Platform$file.sep,"estimate",.Platform$file.sep,"validation_plots_dynamic",.Platform$file.sep))){
                dir.create(paste0(path_results,.Platform$file.sep,"estimate",.Platform$file.sep,"validation_plots_dynamic",.Platform$file.sep))
  
}
  }
```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
if(!dynamic){
#if (is.na(map_years) & is.na(map_seasons)){#if static model
if (!validation){  
  if(existGeoLines) { 
    if (!identical(NA,map_siteAttributes.list) & length(map_siteAttributes.list)!=0){
      rendered <- knit(text = rmd, quiet = TRUE)
      cat("\n \n")
      cat(rendered, sep = "\n")
    }}
}
}
```


```{r echo=FALSE, results='asis', eval=TRUE}
if (!validation){ 
  strExplanation<-"# Model Estimation Performance Diagnostics
Diagnostics are based on the use of conditioned (monitoring-adjusted) predictions. These predictions provide the most accurate reach predictions for use in calibrating the model. The associated residuals and observed to predicted ratios shown in the following section provide the most relevant measures of the accuracy of the model fit to observed loads.

### The diagnostic plots include:
1. Four-plot panel for observed vs. predicted for loads and yields, and log residuals vs. predicted loads and yields

2. Four-plot panel for boxplots of residuals and observed/predicted ratios, normal quantile plot of standardized residuals, and plot of squared residuals vs. predicted loads

3. Plot of conditioned prediction loads vs. unconditioned (simulated) prediction loads

4. Plots of the observed to predicted ratio vs. the area-weighted mean values of the user-selected explanatory variables for the incremental areas between calibration sites (output only if control setting if_corrExplanVars<-'yes' selected and a value of 1 entered for 'parmCorrGroup' column in the 'parameters.csv' file)

5. Boxplots of the observed to predicted loads vs. the decile classes of the total drainage area for the calibration sites

6. Boxplots of the observed to predicted loads vs. the contiguous spatial classes specified by users in the 'classvar' control setting (e.g., HUC-4)

7. Boxplots of the observed to predicted loads vs. the deciles of the land-use class variable specified by users in the 'class_landuse' control setting, with the land-use classes expressed as a percentage of the incremental drainage area extending from the calibration site to the nearest upstream site locations

8. Four-plot panels reported separately for each of the contiguous spatial classes specified for the first variable entry for the 'classvar[1]' control setting. The panels include:  observed vs. predicted loads, observed vs. predicted yields, log residuals vs. predicted loads, and log residuals vs. predicted yields "
  cat(strExplanation)
}
```

```{r pagebreak2, results='asis', echo=FALSE}
if (!validation){ 
  cat("<P style='page-break-before: always'>") 
}
```

```{r  echo=FALSE, results='asis', eval=TRUE}
if (!validation){ 
  cat("## Observed vs. predicted for loads and yields and log residuals vs. predicted loads and yields\n")
}
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"}  
if (!validation){ 
  ##################################################
  # PERFORMANCE METRICS FOR MONITORING ADJUSTMENT
  ##################################################
  create_diagnosticPlotList()$p1$plotFunc(eval(parse(text =create_diagnosticPlotList()$p1$plotParams)))
 
}
```

```{r pagebreak4, results='asis', echo=FALSE}
cat("<P style='page-break-before: always'>") 
```

```{r  echo=FALSE, results='asis', eval=TRUE}
if (!validation){ 
  cat("## Boxplots of residuals and observed/predicted ratios, normal quantile plot of standardized residuals, and plot of squared residuals vs. predicted loads\n")
}
```  

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE,fig.height=8, fig.width=8}  
if (!validation){ 
  list2env(estimate.list$Mdiagnostics.list)
  create_diagnosticPlotList()$p2$plotFunc(eval(parse(text =create_diagnosticPlotList()$p2$plotParams)))
  plotparmList<-create_diagnosticPlotList()$p2$plotParams
}

```

```{r pagebreak5, results='asis', echo=FALSE}
if (!validation){ 
  cat("<P style='page-break-before: always'>") 
}
```

```{r  echo=FALSE, results='asis', eval=TRUE}
if (!validation){ 
  cat("## Conditioned prediction loads vs. unconditioned (simulated) prediction loads\n")
}
```    

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"}  
if (!validation){ 
  create_diagnosticPlotList()$p3$plotFunc(eval(parse(text =create_diagnosticPlotList()$p3$plotParams)))
}

```

```{r pagebreak6, results='asis', echo=FALSE}
if (!validation){ 
  cat("<P style='page-break-before: always'>") 
}
```

```{r  echo=FALSE, results='asis', eval=TRUE}
if (!validation){ 
  cat("## Observed to predicted ratio vs. the area-weighted mean values of the user-selected explanatory variables for the incremental areas between calibration sites \n
Output only if control setting if_corrExplanVars<-'yes' selected and a value of 1 entered for 'parmCorrGroup' column in the 'parameters.csv' file.
")
}

```  

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}    
if (!validation){  
  # Plots of the Obs-Pred ratio vs. the area-weighted mean values of the explanatory variables 
  #   for the incremental areas between calibration sites
  
  if(!identical(Cor.ExplanVars.list,NA)){ 
    corrData<-ratio.obs.pred
    rmd <- sapply(
      1:(length(Cor.ExplanVars.list$names)),
      function(i) {
        
        knit_expand(path_diagnosticCorrChild, i = i,pIndex=4)
      }
    )
    rmd <- paste(rmd, collapse = "\n")
  }
}
```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
if (!validation){ 
  if(!identical(Cor.ExplanVars.list,NA)){ 
    rendered <- knit(text = rmd, quiet = TRUE)
    cat("\n \n")
    cat(rendered, sep = "\n")
  }
}
```


```{r  echo=FALSE, results='asis', eval=TRUE}
if (!validation){ 
  cat("## Boxplots of the observed to predicted loads vs. the decile classes of the total drainage area for the calibration sites\n
")
}
```  

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"}    
if (!validation){ 
  create_diagnosticPlotList()$p5$plotFunc(eval(parse(text =create_diagnosticPlotList()$p5$plotParams)))
}

``` 

```{r pagebreak7, results='asis', echo=FALSE}
if (!validation){ 
  cat("<P style='page-break-before: always'>") 
}
```

```{r  echo=FALSE, results='asis', eval=TRUE}
if (!validation){ 
   if (!identical(classvar,"sitedata.demtarea.class")){
  cat("## Boxplots of the observed to predicted loads vs. the contiguous spatial classes specified by users in the 'classvar' control setting (e.g., HUC-4) \n
")
   }
}
```  

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}
if (!validation){ 
  # "classvar" regions
  
  if (!identical(classvar,"sitedata.demtarea.class")){
    boxvar<-ratio.obs.pred
    rmd <- sapply(
      1:(length(classvar)),
      function(k) {
        knit_expand(path_diagnosticClassvarChild, k = k, pIndex=6)
      }
    )
    rmd <- paste(rmd, collapse = "\n")
  }
}
```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
if (!validation){ 
  if (!identical(classvar,"sitedata.demtarea.class")){
    rendered <- knit(text = rmd, quiet = TRUE)
    cat("\n \n")
    cat(rendered, sep = "\n")
  }
}
```



```{r  echo=FALSE, results='asis', eval=TRUE}
if (!validation){ 
    if(!is.na( class_landuse[1])){
  cat("## Boxplots of the observed to predicted loads vs. the deciles of the land-use class variable specified by users in the 'class_landuse' control setting\n
The land-use classes expressed as a percentage of the incremental drainage area extending from the calibration site to the nearest upstream site locations
")
    }
}
```  

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}
if (!validation){ 
  # 'classvar2" decile boxplots
  
  if(!is.na( class_landuse[1])){
    boxvar<-ratio.obs.pred
    rmd2 <- sapply(
      1:(length(classvar2)),
      function(l) {
        knit_expand(path_diagnosticClassLandChild, l = l, pIndex=7)
      }
    )
    rmd2 <- paste(rmd2, collapse = "\n")
  }
}
```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
if (!validation){ 
  if(!is.na( class_landuse[1])){
    rendered2 <- knit(text = rmd2, quiet = TRUE)
    cat("\n \n")
    cat(rendered2, sep = "\n")
  }
}
```



```{r  echo=FALSE, results='asis', eval=TRUE}
if (!validation){ 
  cat("## Four-plot panels reported separately for each of the contiguous spatial classes specified for the first variable entry for the 'classvar[1]' control setting\n
The panels include:  observed vs. predicted loads, observed vs. predicted yields, log residuals vs. predicted loads, and log residuals vs. predicted yields 
")
}
```  

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}
##################################################



# Obtain CLASS region numbers
grp <- table(class[,1])   # get labels
xx <- as.data.frame(grp)  # convert table to dataframe...
grp <- as.numeric(levels(xx$Var1)[xx$Var1])  # convert factor levels to numeric values


```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}
if (!validation){
  simulation<-FALSE
  rmd3 <- sapply(
    1:(length(grp)),
    function(i) {
      knit_expand(path_diagnosticContiguousChild, i = i,pIndex=8)
    }
  )
  rmd3 <- paste(rmd3, collapse = "\n")
}
```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
if (!validation){ 
  rendered3 <- knit(text = rmd3, quiet = TRUE)
  cat("\n \n")
  cat(rendered3, sep = "\n")
}
```

```{r pagebreak7b, results='asis', echo=FALSE}

cat("<P style='page-break-before: always'>") 

```

```{r echo=FALSE, results='asis', eval=TRUE}
strExplanation<-paste0("# Model Simulation Performance Diagnostics
Diagnostics are based on the use of unconditioned predictions (i.e., predictions that are not adjusted for monitoring loads). These predictions (and the associated residuals and observed to predicted ratios shown in the following section) provide the best measure of the predictive skill of the estimated model in simulation mode. The simulated predictions are computed using mean coefficients from the NLLS model estimated with monitoring-adjusted (conditioned) predictions. \n
### The diagnostic plots include:
1. Four-plot panel for observed vs. predicted for loads and yields, and log residuals vs. predicted loads and yields

2. Four-plot panel for boxplots of residuals and observed/predicted ratios, normal quantile plot of standardized residuals, and plot of squared residuals vs. predicted loads

3. Plot of conditioned prediction loads vs. unconditioned (simulated) prediction loads\n

")
if (!validation){ 
  strExplanation<-paste0(strExplanation,
                         "4. Plots of the observed to predicted ratio vs. the area-weighted mean values of the user-selected explanatory variables for the incremental areas between calibration sites (output only if control setting if_corrExplanVars<-'yes' selected and a value of 1 entered for 'parmCorrGroup' column in the 'parameters.csv' file)\n

5. Boxplots of the observed to predicted loads vs. the decile classes of the total drainage area for the calibration sites

6. Boxplots of the observed to predicted loads vs. the contiguous spatial classes specified by users in the 'classvar' control setting (e.g., HUC-4)

7. Boxplots of the observed to predicted loads vs. the deciles of the land-use class variable specified by users in the 'class_landuse' control setting, with the land-use classes expressed as a percentage of the incremental drainage area extending from the calibration site to the nearest upstream site locations

8. Four-plot panels reported separately for each of the contiguous spatial classes specified for the first variable entry for the 'classvar[1]' control setting. The panels include:  observed vs. predicted loads, observed vs. predicted yields, 
log residuals vs. predicted loads, and log residuals vs. predicted yields ")
}else{
  strExplanation<-paste0(strExplanation,
                         "4. Boxplots of the observed to predicted loads vs. the decile classes of the total drainage area for the calibration sites

5. Boxplots of the observed to predicted loads vs. the contiguous spatial classes specified by users in the 'classvar' control setting (e.g., HUC-4)

6. Boxplots of the observed to predicted loads vs. the deciles of the land-use class variable specified by users in the 'class_landuse' control setting, with the land-use classes expressed as a percentage of the incremental drainage area extending from the calibration site to the nearest upstream site locations

7. Four-plot panels reported separately for each of the contiguous spatial classes specified for the first variable entry for the 'classvar[1]' control setting. The panels include:  observed vs. predicted loads, observed vs. predicted yields, 
log residuals vs. predicted loads, and log residuals vs. predicted yields ")                     
}
cat(strExplanation)
```

```{r pagebreak8a, results='asis', echo=FALSE}
cat("<P style='page-break-before: always'>") 
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"}  
##################################################
# PERFORMANCE METRICS FOR NO MONITORING ADJUSTMENT
##################################################  
  create_diagnosticPlotList()$p9$plotFunc(eval(parse(text =create_diagnosticPlotList()$p9$plotParams)))



```

```{r pagebreak8, results='asis', echo=FALSE}
cat("<P style='page-break-before: always'>") 
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"}  

##################################  
  create_diagnosticPlotList()$p10$plotFunc(eval(parse(text =create_diagnosticPlotList()$p10$plotParams)))

```

```{r pagebreak9, results='asis', echo=FALSE}
if (!validation){ 
  cat("<P style='page-break-before: always'>") 
}
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"}  
if (!validation){ 
  ##############################  
  # Plots of the Obs-Pred ratio vs. the area-weighted mean values of the explanatory variables 
  #   for the incremental areas between calibration sites
  
  if(!identical(Cor.ExplanVars.list,NA)){ 
    corrData<-pratio.obs.pred
    rmd <- sapply(
      1:(length(Cor.ExplanVars.list$names)),
      function(i) {
        
        knit_expand(path_diagnosticCorrChild, i = i,pIndex=11)
      }
    )
    rmd <- paste(rmd, collapse = "\n")
  }
}
```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
if (!validation){  
  if(!identical(Cor.ExplanVars.list,NA)){ 
    rendered <- knit(text = rmd, quiet = TRUE)
    cat("\n \n")
    cat(rendered, sep = "\n")
  }
}
```

```{r pagebreak9b, results='asis', echo=FALSE}

cat("<P style='page-break-before: always'>") 

```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"}  
##########################
# Diagnostics for Ratio by class (one plot per page)
 
plotParams<-eval(parse(text =create_diagnosticPlotList()$p12$plotParams))
#plotParams$ratio.obs.pred<-pratio.obs.pred
  create_diagnosticPlotList()$p12$plotFunc(plotParams)



```

```{r pagebreak10, results='asis', echo=FALSE}
cat("<P style='page-break-before: always'>") 
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"}  
# "classvar" regions
if (!identical(classvar,"sitedata.demtarea.class")){
  boxvar<-pratio.obs.pred
  rmd4 <- sapply(
    1:(length(classvar)),
    function(k) {
      knit_expand(path_diagnosticClassvarChild, k = k, pIndex=13)
    }
  )
  rmd4 <- paste(rmd4, collapse = "\n")
}
```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
if (!identical(classvar,"sitedata.demtarea.class")){
  rendered4 <- knit(text = rmd4, quiet = TRUE)
  cat("\n \n")
  cat(rendered4, sep = "\n")
}
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"}  
# 'classvar2" decile boxplots
if(!is.na( class_landuse[1])){
  boxvar<-pratio.obs.pred
  rmd5 <- sapply(
    1:(length(classvar2)),
    function(l) {
      knit_expand(path_diagnosticClassLandChild, l = l,pIndex=14)
    }
  )
  rmd5 <- paste(rmd5, collapse = "\n")
}
```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
if(!is.na( class_landuse[1])){
  rendered5 <- knit(text = rmd5, quiet = TRUE)
  cat("\n \n")
  cat(rendered5, sep = "\n")
}
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, out.width="750px", out.height="750px"}  
##################################################
# Diagnostics by CLASS (contiguous geographic units)




```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}
simulation<-TRUE
rmd6 <- sapply(
  1:(length(grp)),
  function(i) {
    knit_expand(path_diagnosticContiguousChild, i = i,pIndex=15)
  }
)
rmd6 <- paste(rmd6, collapse = "\n")

```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}

rendered6 <- knit(text = rmd6, quiet = TRUE)
cat("\n \n")
cat(rendered6, sep = "\n")

```

```{r echo=FALSE, results='asis', eval=TRUE}

if(existGeoLines & !dynamic) { 
  strExplanation<-"# Maps of Model Residuals and Observed to Predicted Ratios for the Calibration Sites
### The maps include:
1. Log residuals, based on monitoring conditioned predictions (i.e., Model Estimation Log Residuals)

2. Log residuals, based on the unconditioned predictions (i.e., Model Simulation Log Residuals)

3. Standardized residuals based on the monitoring conditioned predictions

4. Ratio of observed to predicted loads for the conditioned predictions (i.e., Model Estimation Ratio)\n

5. Ratio of observed to predicted load for the unconditioned predictions (i.e., Model Simulation Ratio) "
  cat(strExplanation)
}
```

```{r pagebreak11, results='asis', echo=FALSE}
cat("<P style='page-break-before: always'>") 
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}
#################
# Residual MAPS
#################
if (!dynamic){
        mapdata <- data.frame(lat=sitedata$lat,lon=sitedata$lon,
                              Resids = estimate.list$Mdiagnostics.list$Resids,
                              ratio.obs.pred = estimate.list$Mdiagnostics.list$ratio.obs.pred,
                              pResids = estimate.list$Mdiagnostics.list$pResids, 
                              pratio.obs.pred = estimate.list$Mdiagnostics.list$pratio.obs.pred,
                              standardResids = estimate.list$Mdiagnostics.list$standardResids) 
}

if (!validation){

    residmapTypes<-c("threshold-above","threshold-below","all")
    mapColumn<-"Resids"
    strTitle<-"Model Estimation Log Residuals"
    
if (!dynamic){
  rmd<-diagnosticResidMapExec(validation,existGeoLines,residmapTypes,mapColumn,strTitle,dynamic,
                                 sitedata, Resids,pResids,ratio.obs.pred,pratio.obs.pred,standardResids,
                                 path_diagnosticDiagMapChild,path_outputMapsChild,path_outputMaps,
                                 map_years,map_seasons,mapPageGroupBy,mapsPerPage,
                                 enable_plotlyMaps,add_plotlyVars,path_gis,LineShapeGeo,GeoLines,
                                 data_names,mapping.input.list,batch_mode)
}else{
diagnosticResidMapExec(validation,existGeoLines,residmapTypes,mapColumn,strTitle,dynamic,
                                 sitedata, Resids,pResids,ratio.obs.pred,pratio.obs.pred,standardResids,
                                 path_diagnosticDiagMapChild,path_outputMapsChild,path_outputMaps,
                                 map_years,map_seasons,mapPageGroupBy,mapsPerPage,
                                 enable_plotlyMaps,add_plotlyVars,path_gis,LineShapeGeo,GeoLines,
                                 data_names,mapping.input.list,batch_mode)
}
}
```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
if (!validation){
  if(existGeoLines) { 
    if(!dynamic){
    rendered <- knit(text = rmd, quiet = TRUE)
    cat("\n \n")
    cat(rendered, sep = "\n")
    }
  }
}
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}
#################
# Residual MAPS
#################


# Setup GEOLINES basemap, if available

#8.8.17 if(!is.na(LineShapeGeo)) {

  # Single map of prediction residuals (8 classes) - no monitoring adjustment
  
  residmapTypes<-c("threshold-above","threshold-below","all")
  mapColumn<-"pResids"
  strTitle<-"Model Simulation Log Residuals"
  

  if (!dynamic){
  rmd<-diagnosticResidMapExec(validation,existGeoLines,residmapTypes,mapColumn,strTitle,dynamic,
                                 sitedata, Resids,pResids,ratio.obs.pred,pratio.obs.pred,standardResids,
                                 path_diagnosticDiagMapChild,path_outputMapsChild,path_outputMaps,
                                 map_years,map_seasons,mapPageGroupBy,mapsPerPage,
                                 enable_plotlyMaps,add_plotlyVars,path_gis,LineShapeGeo,GeoLines,
                                 data_names,mapping.input.list,batch_mode)
}else{
diagnosticResidMapExec(validation,existGeoLines,residmapTypes,mapColumn,strTitle,dynamic,
                                 sitedata, Resids,pResids,ratio.obs.pred,pratio.obs.pred,standardResids,
                                 path_diagnosticDiagMapChild,path_outputMapsChild,path_outputMaps,
                                 map_years,map_seasons,mapPageGroupBy,mapsPerPage,
                                 enable_plotlyMaps,add_plotlyVars,path_gis,LineShapeGeo,GeoLines,
                                 data_names,mapping.input.list,batch_mode)
}

```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
if(!dynamic){
if(existGeoLines) { 
  rendered <- knit(text = rmd, quiet = TRUE)
  cat("\n \n")
  cat(rendered, sep = "\n")
}
}
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}    

 if (!validation){

    residmapTypes<-c("threshold-above","threshold-below","all")
    mapColumn<-"standardResids"

    strTitle<-"Model Estimation Standardized Residuals"
    
      if (!dynamic){
  rmd<-diagnosticResidMapExec(validation,existGeoLines,residmapTypes,mapColumn,strTitle,dynamic,
                                 sitedata, Resids,pResids,ratio.obs.pred,pratio.obs.pred,standardResids,
                                 path_diagnosticDiagMapChild,path_outputMapsChild,path_outputMaps,
                                 map_years,map_seasons,mapPageGroupBy,mapsPerPage,
                                 enable_plotlyMaps,add_plotlyVars,path_gis,LineShapeGeo,GeoLines,
                                 data_names,mapping.input.list,batch_mode)
}else{
diagnosticResidMapExec(validation,existGeoLines,residmapTypes,mapColumn,strTitle,dynamic,
                                 sitedata, Resids,pResids,ratio.obs.pred,pratio.obs.pred,standardResids,
                                 path_diagnosticDiagMapChild,path_outputMapsChild,path_outputMaps,
                                 map_years,map_seasons,mapPageGroupBy,mapsPerPage,
                                 enable_plotlyMaps,add_plotlyVars,path_gis,LineShapeGeo,GeoLines,
                                 data_names,mapping.input.list,batch_mode)
}
    

 }

```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
if(!dynamic){
if (!validation){
  if(existGeoLines) { 
    rendered <- knit(text = rmd, quiet = TRUE)
    cat("\n \n")
    cat(rendered, sep = "\n")
  }
}
}

```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}    

 if (!validation){

    ##########################
    # Map Ratios observed to predicted 
    
    residmapTypes<-c("threshold-above","threshold-below","all")
    mapColumn<-"ratio.obs.pred"

    strTitle<-"Model Estimation Obs.Pred Ratio"
        if (!dynamic){
  rmd<-diagnosticResidMapExec(validation,existGeoLines,residmapTypes,mapColumn,strTitle,dynamic,
                                 sitedata, Resids,pResids,ratio.obs.pred,pratio.obs.pred,standardResids,
                                 path_diagnosticDiagMapChild,path_outputMapsChild,path_outputMaps,
                                 map_years,map_seasons,mapPageGroupBy,mapsPerPage,
                                 enable_plotlyMaps,add_plotlyVars,path_gis,LineShapeGeo,GeoLines,
                                 data_names,mapping.input.list,batch_mode)
}else{
diagnosticResidMapExec(validation,existGeoLines,residmapTypes,mapColumn,strTitle,dynamic,
                                 sitedata, Resids,pResids,ratio.obs.pred,pratio.obs.pred,standardResids,
                                 path_diagnosticDiagMapChild,path_outputMapsChild,path_outputMaps,
                                 map_years,map_seasons,mapPageGroupBy,mapsPerPage,
                                 enable_plotlyMaps,add_plotlyVars,path_gis,LineShapeGeo,GeoLines,
                                 data_names,mapping.input.list,batch_mode)
}  

 }

```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
if(!dynamic){
if (!validation){ 
  if(existGeoLines) { 
    rendered <- knit(text = rmd, quiet = TRUE)
    cat("\n \n")
    cat(rendered, sep = "\n")
  }
}
}
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}    


  ##########################
  # Map Ratios observed to predicted for no monitoring adjustment
  
  residmapTypes<-c("threshold-above","threshold-below","all")
  mapColumn<-"pratio.obs.pred"

  strTitle<-"Model Simulation Obs.Pred Ratio"
      if (!dynamic){
  rmd<-diagnosticResidMapExec(validation,existGeoLines,residmapTypes,mapColumn,strTitle,dynamic,
                                 sitedata, Resids,pResids,ratio.obs.pred,pratio.obs.pred,standardResids,
                                 path_diagnosticDiagMapChild,path_outputMapsChild,path_outputMaps,
                                 map_years,map_seasons,mapPageGroupBy,mapsPerPage,
                                 enable_plotlyMaps,add_plotlyVars,path_gis,LineShapeGeo,GeoLines,
                                 data_names,mapping.input.list,batch_mode)
}else{
diagnosticResidMapExec(validation,existGeoLines,residmapTypes,mapColumn,strTitle,dynamic,
                                 sitedata, Resids,pResids,ratio.obs.pred,pratio.obs.pred,standardResids,
                                 path_diagnosticDiagMapChild,path_outputMapsChild,path_outputMaps,
                                 map_years,map_seasons,mapPageGroupBy,mapsPerPage,
                                 enable_plotlyMaps,add_plotlyVars,path_gis,LineShapeGeo,GeoLines,
                                 data_names,mapping.input.list,batch_mode)
}  


```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
if(!dynamic){
if(existGeoLines) { 
  rendered <- knit(text = rmd, quiet = TRUE)
  cat("\n \n")
  cat(rendered, sep = "\n")
}
}
```

