---
title: "diagnosticSensitivity"
author: ""
date: "`r format(Sys.time(), '%m-%d-%Y')`"
output: html_document
params:
  file.output.list: file.output.list
  path_paramSensChild: path_paramSensChild
  classvar: classvar
  estimate.list: estimate.list
  DataMatrix.list: DataMatrix.list
  SelParmValues: SelParmValues
  reach_decay_specification: reach_decay_specification
  reservoir_decay_specification: reservoir_decay_specification
  subdata: subdata
  sitedata.demtarea.class: sitedata.demtarea.class
  mapping.input.list: mapping.input.list

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE)
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE}
#unpack params
  file.output.list<-params$file.output.list
path_paramSensChild<-params$path_paramSensChild
  classvar<-params$classvar
  estimate.list<-params$estimate.list
  DataMatrix.list<-params$DataMatrix.list
  SelParmValues<-params$SelParmValues
  reach_decay_specification<-params$reach_decay_specification
  reservoir_decay_specification<-params$reservoir_decay_specification
  subdata<-params$subdata
  sitedata.demtarea.class<-params$sitedata.demtarea.class
  mapping.input.list<-params$mapping.input.list

  
    unPackList(lists = list(SelParmValues = SelParmValues,
                          JacobResults = estimate.list$JacobResults,
                          file.output.list = file.output.list,
                          mapping.input.list = mapping.input.list),
             parentObj = list(NA,
                              NA,
                              NA,
                              NA))
    
    # contiguous class variables by sites
  class <- array(0,dim=c(nrow=nrow(sitedata),ncol=length(classvar))) 
  for (k in 1:length(classvar)) { 
    for (i in 1:nrow(sitedata)) {
      class[i,k] <- as.numeric(eval(parse(text=paste("sitedata$",classvar[k],"[",i,"]",sep=""))))
    } 
  }
  depvar <- subdata$depvar
  xclass <- eval(parse(text=paste("subdata$",classvar[1],sep="")))
```

```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, fig.height=8, fig.width=8} 
 # required SPARROW estimated coefficients (oEstimate, Parmnames)
  Estimate <- oEstimate  # initial baseline estimates
  
  # obtain baseline predictions all reaches
  predict <- predictSensitivity(Estimate,estimate.list,DataMatrix.list,SelParmValues,
                                reach_decay_specification,reservoir_decay_specification,subdata)
  
  apredict <- predict
  apredict_sum <- matrix(1,nrow=length(depvar),ncol=length(Estimate))
  
  ct <- length(Estimate)
  xiqr <- matrix(0,nrow=4,ncol=sum(ct))
  xmed <- numeric(sum(ct))
  xparm <- character(sum(ct))
  xvalue2 <- numeric(sum(ct))
  xsens <- matrix(0,nrow=sum(depvar > 0),ncol=length(Estimate))
  
  for (i in 1:length(Estimate)) {
    if(betaconstant[i] == 0) {     # an estimated parameter
      #  adjust parameter by 1%
      AEstimate <- Estimate
      AEstimate[i] <- Estimate[i] * 0.99
      apredict <- predictSensitivity(AEstimate,estimate.list,DataMatrix.list,SelParmValues,
                                     reach_decay_specification,reservoir_decay_specification,subdata)
      apredict_sum[,i] <- abs((apredict-predict)/predict*100) / 1.0  # change relative to 1% change
    }
  }
```

 
```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, fig.height=8, fig.width=8}  
  # select site sensitivities 
  #   (only plot for site locations rather than nreach to reduce size of display)
  #j<-0
  #par(mfrow=c(2,2), pch=16)  # 4 plots on one page
  #for (i in 1:length(Estimate)) {
  #  x1 <- apredict_sum[,i]
  #  xx <- data.frame(x1,depvar,xclass)
  #  parmsens <- xx[(xx$depvar > 0), ] 
  #  boxplot(parmsens$x1 ~ parmsens$xclass,xlab=classvar[1],ylab="Prediction Change (%) Relative to 1% Change",las = 2)
  #  title(bquote(paste("Parameter Sensitivity:  ",.(Parmnames[i]))))  
  #  xvalue2[i] <- i
  #  xiqr[,i] <- quantile(parmsens$x1, c(0.10,0.25,0.75,0.90)) 
  #  xmed[i] <- median(parmsens$x1)
  #  xparm[i] <- Parmnames[i]
  #  xsens[,i] <- parmsens$x1   # sensitivites for all calibration sites
  #}
  


rmd <- sapply(
  1:(length(Estimate)),
  function(i) {
  
   knit_expand(path_paramSensChild, i = i)
  }
)
rmd <- paste(rmd, collapse = "\n")

```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}

rendered <- knit(text = rmd, quiet = TRUE)
cat("\n \n")
cat(rendered, sep = "\n")

```


```{r, eval=TRUE, echo=FALSE,warning=FALSE, message = FALSE, fig.height=8, fig.width=8} 
for (i in 1:length(Estimate)) {
    x1 <- apredict_sum[,i]
    xx <- data.frame(x1,depvar,xclass)
    parmsens <- xx[(xx$depvar > 0), ] 
    xvalue2[i] <- i
    xiqr[,i] <- quantile(parmsens$x1, c(0.10,0.25,0.75,0.90)) 
    xmed[i] <- median(parmsens$x1)
    xparm[i] <- Parmnames[i]
    xsens[,i] <- parmsens$x1   # sensitivites for all calibration sites
}   
  # save results to directory and global environment
  sensitivities.list <- named.list(xparm,xmed,xiqr,xsens)
  objfile <- paste(path_results,.Platform$file.sep,"estimate",.Platform$file.sep,run_id,"_sensitivities.list",sep="") 
  save(sensitivities.list,file=objfile)
  assign("sensitivities.list",sensitivities.list,envir = .GlobalEnv)
  
  # Plot median and IQR for each parameter
  xx <- xiqr[1,(xiqr[1,]>0)]  
  xminimum <- min(xx)
  xminimum <- ifelse(is.infinite(xminimum),0,xminimum)
  xmed <- ifelse( xmed == 0,xminimum,xmed)
  xiqr <- ifelse( xiqr == 0,xminimum,xiqr)
  
  xupper <- xiqr[3,] - xmed
  xlower <- xmed - xiqr[2,]
  supper <- xiqr[4,] - xmed
  slower <- xmed - xiqr[1,]
  
  xupper <- ifelse(xupper == 0,xminimum,xupper)
  supper <- ifelse(supper == 0,xminimum,supper)
  xlower <- ifelse(xlower == 0,xminimum,xlower)
  slower <- ifelse(slower == 0,xminimum,slower)
  
  xx <- data.frame(xmed,xlower,xupper,supper,slower,xparm)
  xx <- xx[with(xx,order(xx$xmed)), ]  
  
  ymin <- min(xiqr)
  ymax <- max(xiqr)
  
  # Arithmetic y axis
  par(mfrow=c(1,1), pch=16)    # 1 plots on one page
  plotCI(x=xvalue2, y=xx$xmed, uiw=xx$supper,liw=xx$slower,ylim=c(ymin,ymax),
         col="black",barcol="blue",pch=19,
         ylab="CHANGE IN PREDICTED VALUES (%)",xlab=" ",
         gap=0,
         las = 2,     # axis labels vertical
         xaxt = "n",   # Dont print x-axis
         xlim=c(1,length(Estimate))
  )
  axis(side=1, at=1:(length(Estimate)), labels=xx$xparm, cex.axis=0.8, las = 2)
  title("PARAMETER SENSITIVITY TO 1% CHANGE")
  
  plotCI(x=xvalue2, y=xx$xmed, uiw=xx$xupper,liw=xx$xlower,ylim=c(ymin,ymax),
         col="black",barcol="red",pch=19,
         gap=0,
         xaxt = "n",   # Dont print x-axis
         add=TRUE
  )
  
  # Log y axis
  par(mfrow=c(1,1), pch=16)    # 1 plots on one page
  plotCI(x=xvalue2, y=xx$xmed, uiw=xx$supper,liw=xx$slower,ylim=c(ymin,ymax),
         col="black",barcol="blue",pch=19,log="y",
         ylab="CHANGE IN PREDICTED VALUES (%)",xlab=" ",
         gap=0,
         las = 2,     # axis labels vertical
         xaxt = "n",   # Dont print x-axis
         xlim=c(1,length(Estimate))
  )
  axis(side=1, at=1:(length(Estimate)), labels=xx$xparm, cex.axis=0.8, las = 2)
  title("PARAMETER SENSITIVITY TO 1% CHANGE")
  
  plotCI(x=xvalue2, y=xx$xmed, uiw=xx$xupper,liw=xx$xlower,ylim=c(ymin,ymax),
         col="black",barcol="red",pch=19,log="y",
         gap=0,
         xaxt = "n",   # Dont print x-axis
         add=TRUE
  )
```
